//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasketProducts
    {
        public int idBasketProduct { get; set; }
        public string nameProductB { get; set; }
        public string customerB { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> expiration { get; set; }
        public Nullable<double> priceB { get; set; }
        public Nullable<double> sale { get; set; }
        public string barcode { get; set; }
    }
}
